services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch-lab
    ports:
      - "8123:8123"
      - "9005:9000"
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=admin_admin
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
